dist: xenial
language: node_js
node_js:
  - 10
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"
  - yarn install
jobs:
  include:
    - stage: "Compile"
      script: make compile
    - stage: "Migrate"
      before_script: npx ganache-cli -p 9545 start &
      script: npx truffle migrate --reset --network development
    - stage: "Tests"
      before_script: npx ganache-cli -p 9545 start &
      script: npx truffle test --network development
    - stage: "Coverage"
      script: make coverage
